In [1]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
list1=[int(input()) for i in range(5)]
list2=[int(input()) for i in range(5)]
array1=np.array(list1)
array2=np.array(list2)
print(array1)
print(array2)
conc=np.concatenate((array1,array2),axis=None)
sort1=np.sort(conc)
print(conc)
print(sort1)

1
4
6
7
8
2
9
6
7
4
[1 4 6 7 8]
[2 9 6 7 4]
[1 4 6 7 8 2 9 6 7 4]
[1 2 4 4 6 6 7 7 8 9]


In [3]:
array3=np.array([[2,4,1],[3,6,4]])
print(array3.ndim)
print(array3.size)

2
6


In [4]:
import numpy as np
arr=np.array([2,3,4,5,6,7])
print(arr)
arr=arr[:,np.newaxis]
print(arr)
arr=np.expand_dims(arr,2)
print(arr)

[2 3 4 5 6 7]
[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]]


In [5]:
a=np.array([1,2])
b=np.array([4,5])
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[1 2]
 [4 5]]
[1 2 4 5]


Question 6: How to get unique items and counts of unique items?

In [6]:
a=np.array([1,2,3,4,1,3,6,6,7])
unique_elements,unique_count=np.unique(a,return_counts=True)
print(unique_elements,unique_count)

[1 2 3 4 6 7] [2 1 2 1 2 1]
